"""baseline schema

Revision ID: 116625023967
Revises: 
Create Date: 2026-08-09 20:20:37.609768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116625023967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pokedex_number', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('sp_attack', sa.Integer(), nullable=False),
    sa.Column('sp_defense', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('type1', sa.String(length=255), nullable=False),
    sa.Column('type2', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=255), nullable=False),
    sa.Column('abilities', sa.String(length=255), nullable=True),
    sa.Column('capture_rate', sa.Integer(), nullable=True),
    sa.Column('is_legendary', sa.Integer(), nullable=True),
    sa.Column('percentage_male', sa.Float(), nullable=True),
    sa.Column('base_total', sa.Integer(), nullable=True),
    sa.Column('base_egg_steps', sa.Integer(), nullable=True),
    sa.Column('base_happiness', sa.Integer(), nullable=True),
    sa.Column('experience_growth', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.create_index('ix_pokemon_generation', ['generation'], unique=False)
        batch_op.create_index('ix_pokemon_is_legendary', ['is_legendary'], unique=False)
        batch_op.create_index('ix_pokemon_name', ['name'], unique=False)
        batch_op.create_index('ix_pokemon_type1', ['type1'], unique=False)
        batch_op.create_index('ix_pokemon_type1_generation', ['type1', 'generation'], unique=False)
        batch_op.create_index('ix_pokemon_type1_type2', ['type1', 'type2'], unique=False)
        batch_op.create_index('ix_pokemon_type2', ['type2'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('pokeballs', sa.Integer(), nullable=False),
    sa.Column('quiz_questions_answered', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.create_index('ix_user_pokemon_pokemon_id', ['pokemon_id'], unique=False)
        batch_op.create_index('ix_user_pokemon_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.drop_index('ix_user_pokemon_user_id')
        batch_op.drop_index('ix_user_pokemon_pokemon_id')

    op.drop_table('user_pokemon')
    op.drop_table('message')
    op.drop_table('user')
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_index('ix_pokemon_type2')
        batch_op.drop_index('ix_pokemon_type1_type2')
        batch_op.drop_index('ix_pokemon_type1_generation')
        batch_op.drop_index('ix_pokemon_type1')
        batch_op.drop_index('ix_pokemon_name')
        batch_op.drop_index('ix_pokemon_is_legendary')
        batch_op.drop_index('ix_pokemon_generation')

    op.drop_table('pokemon')
    # ### end Alembic commands ###
